### ISSUE TITLE
Theme from vscode

### ISSUE THREAD

**Issue by byBenPuls** [rohitprofc/rohitprofc#1]
Hello, can you say me your vscode theme from this photo?

![image](https://github.com/user-attachments/assets/e245c461-8cff-40d7-bd14-2d29e9676df4)

It's screenshot from microsoft/vscode [issue](https://github.com/microsoft/vscode/issues/195191#issuecomment-1766558028) from your answer.

**Comment by rohitprofc** [comment]
### Sure! @byBenPuls - Closes #1 
### Theme name is "Bearded Theme Surprising Blueberry"
### You can find it [here](https://marketplace.visualstudio.com/items?itemName=BeardedBear.beardedtheme)

**Comment by rohitprofc** [comment]
### Sure! @byBenPuls - Closes #1 
### Theme name is "Bearded Theme Surprising Blueberry"
### You can find it [here](https://marketplace.visualstudio.com/items?itemName=BeardedBear.beardedtheme)
